#name       ワークフローのなまえ
#on         動作イベント
#jobs       ジョブの単位
#runs-on    ジョブを実行するマシン
#steps      実行されるステップをグループ化
#uses       ここで指定したアクションが実行される
#run        プログラムを実行するようにジョブに指示する
#name       runの手前に書くと名前を付けることができる

name: auto_merge
on: workflow_dispatch
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write    #プッシュ権限を与える
    steps:
      - name: リポジトリのクローン
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全ての履歴を取得

      - name: 設定 - Gitユーザー名とメールアドレス
        run: |
          git config --local user.email "yagikundayo@gmail.com"
          git config --local user.name "YagiSosuke"

      - name: リモートブランチをフェッチ
        run: git fetch --all

      #ここから、mainブランチの更新を行います
      - name: mainブランチをチェックアウト
        run: |
          git checkout main
          git pull origin main

      - name: test1ブランチをマージ
        run: git merge origin/test1
        
      - name: test2ブランチをマージ
        run: git merge origin/test2
        
      #ここから、test1ブランチの更新を行います
      - name: test1ブランチをチェックアウト
        run: |
          git checkout test1
          git pull origin test1

      - name: mainブランチをマージ
        run: git merge main
        
      #ここから、test2ブランチの更新を行います
      - name: test2ブランチをチェックアウト
        run: |
          git checkout test2
          git pull origin test2

      - name: mainブランチをマージ
        run: git merge main

      
      - name: 変更をプッシュ
        run: |
          git push origin main
          git push origin test1
          git push origin test2
