#name       ワークフローのなまえ
#on         動作イベント
#jobs       ジョブの単位
#runs-on    ジョブを実行するマシン
#steps      実行されるステップをグループ化
#uses       ここで指定したアクションが実行される
#run        プログラムを実行するようにジョブに指示する
#name       runの手前に書くと名前を付けることができる

name: auto_merge
on: workflow_dispatch
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write    #プッシュ権限を与える
    steps:
      - name: リポジトリのクローン
        uses: actions/checkout@v4

      - name: リモートブランチをフェッチ
        run: git fetch --all
          
      - name: test1ブランチをチェックアウト
        run: |
          if git branch -r | grep -q "origin/test1"; then
            git checkout -b test1 origin/test1
          else
            echo "リモートブランチにtest1ブランチが存在しません" && exit 1
          fi

      - name: mainブランチをチェックアウト
        run: git checkout main

      - name: test1ブランチをマージ
        run: git merge test1 --allow-unrelated-histories
        
      - name: 変更をプッシュ
        run: git push origin main
