#name       ワークフローのなまえ
#on         動作イベント
#jobs       ジョブの単位
#runs-on    ジョブを実行するマシン
#steps      実行されるステップをグループ化
#uses       ここで指定したアクションが実行される
#run        プログラムを実行するようにジョブに指示する
#name       runの手前に書くと名前を付けることができる

name: auto_merge
on: workflow_dispatch
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのクローン
        uses: actions/checkout@v4

      - name: リモートブランチを確認
        run: git branch -r

      - name: mainブランチをチェックアウト
        run: git checkout main

      - name: リモートブランチをフェッチ
        run: git fetch --all

      - name: リモートブランチをローカルにチェックアウト
        run: |
          if git branch -r | grep -q "origin/test1"; then
            git fetch origin test1:test1
          else
            echo "リモートにtest1ブランチが存在しません。" && exit 1
          fi

      - name: test1ブランチをマージ
        run: git merge test1
