#name       ワークフローのなまえ
#on         動作イベント
#jobs       ジョブの単位
#runs-on    ジョブを実行するマシン
#steps      実行されるステップをグループ化
#uses       ここで指定したアクションが実行される
#run        プログラムを実行するようにジョブに指示する
#name       runの手前に書くと名前を付けることができる

name: merge_version_manage_branches
on: workflow_dispatch
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write    #プッシュ権限を与える
    steps:
      - name: リポジトリのクローン
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全ての履歴を取得

      - name: 設定 - Gitユーザー名とメールアドレス
        run: |
          git config --local user.email "yagikundayo@gmail.com"
          git config --local user.name "YagiSosuke"
      - name: リモートブランチをフェッチ
        run: git fetch --all

      - name: バージョンファイル名ファイルから操作するブランチ名を首都tく
        id: branches
        run: |
          mapfile -t branches < .github/config/dev_version_manage_branch_names.txt
          echo "::set-output name=branches::$branches"
          length=$(#branches[@])

          #for ((i=1; i<$length; i++)); do
          i=1
          branch=${branches[i]}
          beforeVersion=${branches[i-1]}

          echo "ブランチのマージ [$beforeVersion] -> [$branch]"
          
          #ブランチをチェックアウト
          git checkout $branch
          git pull origin $branch
              
          #beforeVersionをマージ
          git merge $beforeVersion
          git push origin $branch
          #done
